# Generated by Django 5.1 on 2024-08-24 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('ready_in_minutes', models.IntegerField()),
                ('diets', models.CharField(max_length=100)),
                ('servings', models.IntegerField()),
                ('image_url', models.URLField()),
                ('ingredients', models.TextField()),
                ('source_url', models.URLField()),
            ],
        ),
    ]
